from pathlib import Path
lines = []
lines.append('# -*- coding: utf-8 -*-')
lines.append('import ctypes, time, subprocess')
lines.append('from ctypes import wintypes')
lines.append('from pathlib import Path')
lines.append('from datetime import datetime')
lines.append('ROOT = Path(r"C:\\Users\\zhang\\grok-regkit")')
lines.append('LOG = ROOT / "matrix_runs" / "_CODEX_SILENCE_SAFE.log"')
lines.append('LOG.parent.mkdir(exist_ok=True)')
lines.append('user32 = ctypes.windll.user32')
lines.append('SW_SHOWMINNOACTIVE = 7')
lines.append('HWND_BOTTOM = 1')
lines.append('SWP_NOSIZE = 0x0001')
lines.append('SWP_NOACTIVATE = 0x0010')
lines.append('EnumWindows = user32.EnumWindows')
lines.append('EnumWindowsProc = ctypes.WINFUNCTYPE(ctypes.c_bool, wintypes.HWND, wintypes.LPARAM)')
lines.append('IsWindowVisible = user32.IsWindowVisible')
lines.append('GetClassNameW = user32.GetClassNameW')
lines.append('GetWindowThreadProcessId = user32.GetWindowThreadProcessId')
lines.append('ShowWindow = user32.ShowWindow')
lines.append('SetWindowPos = user32.SetWindowPos')
lines.append('def script_pids():')
lines.append('    ps = "Get-CimInstance Win32_Process -Filter \\"Name = \'chrome.exe\'\\" | Where-Object { $_.CommandLine -match \'DrissionPage\\\\userData|DrissionPage/userData\' } | ForEach-Object { $_.ProcessId }"')
lines.append('    try:')
lines.append('        out = subprocess.check_output(["powershell","-NoProfile","-Command",ps], timeout=10, text=True, encoding="utf-8", errors="ignore")')
lines.append('    except Exception:')
lines.append('        return set()')
lines.append('    s=set()')
lines.append('    for line in (out or "").splitlines():')
lines.append('        line=line.strip()')
lines.append('        if line.isdigit(): s.add(int(line))')
lines.append('    return s')
lines.append('def silence(pids):')
lines.append('    if not pids: return 0')
lines.append('    targets=[]')
lines.append('    def cb(hwnd, _lp):')
lines.append('        try:')
lines.append('            if not IsWindowVisible(hwnd): return True')
lines.append('            pid=wintypes.DWORD(); GetWindowThreadProcessId(hwnd, ctypes.byref(pid))')
lines.append('            if int(pid.value) not in pids: return True')
lines.append('            cls=ctypes.create_unicode_buffer(256); GetClassNameW(hwnd, cls, 256)')
lines.append('            if (cls.value or "") not in ("Chrome_WidgetWin_1","Chrome_WidgetWin_0"): return True')
lines.append('            targets.append(int(hwnd))')
lines.append('        except Exception: pass')
lines.append('        return True')
lines.append('    EnumWindows(EnumWindowsProc(cb), 0)')
lines.append('    n=0')
lines.append('    for hwnd in targets:')
lines.append('        try:')
lines.append('            ShowWindow(hwnd, SW_SHOWMINNOACTIVE)')
lines.append('            SetWindowPos(hwnd, HWND_BOTTOM, -32000, 0, 0, 0, SWP_NOSIZE|SWP_NOACTIVATE)')
lines.append('            n+=1')
lines.append('        except Exception: pass')
lines.append('    return n')
lines.append('last=0')
lines.append('while True:')
lines.append('    try:')
lines.append('        pids=script_pids(); n=silence(pids); now=time.time()')
lines.append('        if now-last>20:')
lines.append('            last=now')
lines.append('            with LOG.open("a", encoding="utf-8") as f:')
lines.append('                f.write(f"{datetime.now().isoformat(timespec=chr(115)+chr(101)+chr(99)+chr(111)+chr(110)+chr(100)+chr(115))} script_pids={len(pids)} silenced={n}\\n")')
lines.append('    except Exception as exc:')
lines.append('        try:')
lines.append('            with LOG.open("a", encoding="utf-8") as f: f.write(f"{datetime.now().isoformat()} err={exc}\\n")')
lines.append('        except Exception: pass')
lines.append('    time.sleep(1.2)')
Path(r"C:\Users\zhang\grok-regkit\tools\_silence_safe_drission.py").write_text("\n".join(lines)+"\n", encoding="utf-8")
print("ok", len(lines))