from pathlib import Path
lines = []
def L(s=""):
    lines.append(s)
L("# -*- coding: utf-8 -*-")
L("import json, time, urllib.request")
L("from datetime import datetime")
L("from pathlib import Path")
L('ROOT = Path(r"C:\\Users\\zhang\\grok-regkit")')
L('OUT = ROOT / "matrix_runs"')
L('BOARD = OUT / "_CODEX_MATRIX_18r43_LIVE.md"')
L('SNAP = OUT / "_CODEX_STATUS_18r43.jsonl"')
L('BASE = "http://127.0.0.1:8092"')
L("")
L("def get(path):")
L("    with urllib.request.urlopen(BASE + path, timeout=12) as r:")
L('        return json.loads(r.read().decode("utf-8", "replace"))')
L("")
L("while True:")
L("    try:")
L('        st = get("/api/status")')
L("        try:")
L('            lg = get("/api/logs/snapshot?limit=15")')
L('            lines = [str(x) for x in (lg.get("lines") or [])[-10:]]')
L("        except Exception:")
L("            lines = []")
L("        chrome = edge = dr = 0")
L("        try:")
L("            import psutil")
L('            for p in psutil.process_iter(["name", "cmdline"]):')
L("                try:")
L('                    n = (p.info.get("name") or "").lower()')
L('                    cl = " ".join(p.info.get("cmdline") or [])')
L('                    if n == "chrome.exe":')
L("                        chrome += 1")
L('                        if "DrissionPage" in cl or ".chrome-data" in cl:')
L("                            dr += 1")
L('                    if n == "msedge.exe":')
L("                        edge += 1")
L("                except Exception:")
L("                    pass")
L("        except Exception:")
L("            pass")
L('        now = datetime.now().isoformat(timespec="seconds")')
L("        rec = {")
L('            "ts": now,')
L('            "running": st.get("running"),')
L('            "success": st.get("success"),')
L('            "fail": st.get("fail"),')
L('            "pending_sso": st.get("pending_sso"),')
L('            "awaiting_pool": st.get("awaiting_pool") or st.get("pending_pool") or 0,')
L('            "skipped": st.get("skipped"),')
L('            "target": st.get("target"),')
L('            "phase": st.get("phase"),')
L('            "job_kind": st.get("job_kind"),')
L('            "event": str(st.get("last_event") or "")[:180],')
L('            "chrome": chrome,')
L('            "drission": dr,')
L('            "edge": edge,')
L("        }")
L('        with SNAP.open("a", encoding="utf-8") as f:')
L('            f.write(json.dumps(rec, ensure_ascii=False) + "\\n")')
L("        md = [")
L('            "# 18r43 silent matrix LIVE (Edge-safe)",')
L('            f"updated={now}",')
L("            (")
L('                f"running={rec[\'running\']} ok={rec[\'success\']} fail={rec[\'fail\']} "')
L('                f"pending={rec[\'pending_sso\']} awaiting_pool={rec[\'awaiting_pool\']} "')
L('                f"skip={rec[\'skipped\']} target={rec[\'target\']}"')
L("            ),")
L('            f"phase={rec[\'phase\']} kind={rec[\'job_kind\']}",')
L('            f"chrome={chrome} drission_script={dr} edge={edge} (Edge never minimized)",')
L('            f"event={rec[\'event\']}",')
L('            "",')
L('            "## recent logs",')
L("        ] + [f\"- {x[:200]}\" for x in lines]")
L('        BOARD.write_text("\\n".join(md) + "\\n", encoding="utf-8")')
L("    except Exception as exc:")
L("        try:")
L('            BOARD.write_text("# live error\\n" + datetime.now().isoformat() + "\\n" + str(exc) + "\\n", encoding="utf-8")')
L("        except Exception:")
L("            pass")
L("    time.sleep(20)")
Path("tools/_watch_18r43_live.py").write_text("\n".join(lines) + "\n", encoding="utf-8")
import ast
ast.parse(Path("tools/_watch_18r43_live.py").read_text(encoding="utf-8"))
print("watch ok", Path("tools/_watch_18r43_live.py").stat().st_size)
